# numpy连接

In [1]:
import numpy as np

In [2]:
a_1=np.array([[1,2],[3,4]])
a_2=np.array([[5,6],[7,8]])
#0轴连接
print(np.concatenate((a_1,a_2),axis=0))
#1轴连接
print(np.concatenate((a_1,a_2),axis=1))
#默认连接
print(np.concatenate((a_1,a_2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# 堆叠stack

In [3]:
#和连接差不多
print(np.vstack((a_1,a_2)))
#0轴
print(np.hstack((a_1,a_2)))
#1轴

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# 分割

In [4]:
a=np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [5]:
a_1=np.split(a,2,axis=0)
#括号中数字指的拆成几份
a_1

[array([[0, 1]]), array([[2, 3]])]

In [6]:
a_2=np.split(a,2,axis=1)
a_2

[array([[0],
        [2]]),
 array([[1],
        [3]])]

In [7]:
a_3=np.vsplit(a,2)
a_3

[array([[0, 1]]), array([[2, 3]])]

In [8]:
a_4=np.hsplit(a,2)
a_4

[array([[0],
        [2]]),
 array([[1],
        [3]])]

# 转置

In [9]:
a=np.arange(12).reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [10]:
a_1=np.transpose(a)
a_1

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [11]:
a_2=a.T
a_2

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [12]:
a_3=a.swapaxes(1,0)
a_3

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [13]:
b=np.arange(18).reshape((3,2,3))
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [14]:
b_1=b.swapaxes(1,0)
b_1

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]]])

# pandas

## read_csv

In [15]:
import pandas as pd

In [16]:
fpath='./data/spider.csv'

In [17]:
df=pd.read_csv(fpath,header=None,names=['data','url','title','val1','val2'],index_col='data',usecols=['data','url','title'])
df

url  \
data                                           
2015-4-28            http://www.apinpai.com/   
2015-8-24            http://www.apinpai.com/   
2015-12-14         http://www.movie.com/dor/   
2015-4-2                http://bj.qu114.com/   
2015-12-19         http://www.movie.com/dor/   
...                                      ...   
2015-7-31         http://beijing.faxinxi.cn/   
2015-4-20            http://www.denghuo.com/   
2015-4-2             http://www.yifawang.cn/   
2015-4-15   http://www.wuhan58.com/index.php   
2015-5-16           http://www.favolist.com/   

                                                        title  
data                                                           
2015-4-28                                 采蘑菇的小姑娘;小蓓蕾组合;90;儿歌  
2015-8-24                                         我;张国荣;80;励志  
2015-12-14  《恶棍天使》;2015.12.24;2016.2.13;天津橙子映像传媒有限公司、北京光线影...  
2015-4-2                                     my way;张敬轩;90;励志  
2015-12-19  《失孤》;2015.3.20;2015.5.3;华谊兄弟传媒集团、源合圣影视、映艺娱乐;彭三...  
...                                                       ...  
2015-7-31                                      同道中人;张国荣;80;励志  
2015-4-20                                    忘记拥抱;a-lin;80;伤感  
2015-4-2                                   路...一直都在;陈奕迅;90;励志  
2015-4-15                                     像我一样骄傲;赵传;80;励志  
2015-5-16                                      最冷一天;陈奕迅;90;伤感  

[1396 rows x 2 columns]

In [18]:
df=pd.read_csv(fpath,header=None,names=['data','url','title','val1','val2'])
df

data                               url  \
0      2015-4-28           http://www.apinpai.com/   
1      2015-8-24           http://www.apinpai.com/   
2     2015-12-14         http://www.movie.com/dor/   
3       2015-4-2              http://bj.qu114.com/   
4     2015-12-19         http://www.movie.com/dor/   
...          ...                               ...   
1391   2015-7-31        http://beijing.faxinxi.cn/   
1392   2015-4-20           http://www.denghuo.com/   
1393    2015-4-2           http://www.yifawang.cn/   
1394   2015-4-15  http://www.wuhan58.com/index.php   
1395   2015-5-16          http://www.favolist.com/   

                                                  title   val1     val2  
0                                   采蘑菇的小姑娘;小蓓蕾组合;90;儿歌  216.0  1392.68  
1                                           我;张国荣;80;励志  273.0  1447.17  
2     《恶棍天使》;2015.12.24;2016.2.13;天津橙子映像传媒有限公司、北京光线影...    NaN      NaN  
3                                      my way;张敬轩;90;励志   52.0   337.27  
4     《失孤》;2015.3.20;2015.5.3;华谊兄弟传媒集团、源合圣影视、映艺娱乐;彭三...    NaN      NaN  
...                                                 ...    ...      ...  
1391                                     同道中人;张国荣;80;励志   87.0   927.30  
1392                                   忘记拥抱;a-lin;80;伤感   31.0   684.56  
1393                                 路...一直都在;陈奕迅;90;励志   47.0  1419.74  
1394                                    像我一样骄傲;赵传;80;励志  124.0  1434.67  
1395                                     最冷一天;陈奕迅;90;伤感  103.0  1020.50  

[1396 rows x 5 columns]

In [19]:
df=pd.read_csv(fpath,header=None)
df

0                                 1  \
0      2015-4-28           http://www.apinpai.com/   
1      2015-8-24           http://www.apinpai.com/   
2     2015-12-14         http://www.movie.com/dor/   
3       2015-4-2              http://bj.qu114.com/   
4     2015-12-19         http://www.movie.com/dor/   
...          ...                               ...   
1391   2015-7-31        http://beijing.faxinxi.cn/   
1392   2015-4-20           http://www.denghuo.com/   
1393    2015-4-2           http://www.yifawang.cn/   
1394   2015-4-15  http://www.wuhan58.com/index.php   
1395   2015-5-16          http://www.favolist.com/   

                                                      2      3        4  
0                                   采蘑菇的小姑娘;小蓓蕾组合;90;儿歌  216.0  1392.68  
1                                           我;张国荣;80;励志  273.0  1447.17  
2     《恶棍天使》;2015.12.24;2016.2.13;天津橙子映像传媒有限公司、北京光线影...    NaN      NaN  
3                                      my way;张敬轩;90;励志   52.0   337.27  
4     《失孤》;2015.3.20;2015.5.3;华谊兄弟传媒集团、源合圣影视、映艺娱乐;彭三...    NaN      NaN  
...                                                 ...    ...      ...  
1391                                     同道中人;张国荣;80;励志   87.0   927.30  
1392                                   忘记拥抱;a-lin;80;伤感   31.0   684.56  
1393                                 路...一直都在;陈奕迅;90;励志   47.0  1419.74  
1394                                    像我一样骄傲;赵传;80;励志  124.0  1434.67  
1395                                     最冷一天;陈奕迅;90;伤感  103.0  1020.50  

[1396 rows x 5 columns]

In [20]:
filepath='./data/student.xlsx'
df1=pd.read_excel(filepath)
df1

姓名 性别  班级         生日   身高
0  小红  女   1 1992-01-01  160
1  大红  女   2 1993-01-01  161
2  小明  男   1 1992-02-01  180
3  大明  男   1 1992-03-01  180
4  小亮  男   2 1993-01-01  170

In [21]:
filepath1='./data/saleinfo_month.xls'
df_1=pd.read_excel(filepath1)
df_1

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
0        德系        北京奔驰     SUV    奔驰    奔驰GLA       紧凑        33      202001   
1        德系        北京奔驰     SUV    奔驰    奔驰GLC       中型        49      202001   
2        德系        北京奔驰      轿车    奔驰     奔驰C级       中型        41      202001   
3        德系        北京奔驰      轿车    奔驰     奔驰E级      中大型        53      202001   
4        德系        华晨宝马     SUV    宝马     宝马X1       紧凑        36      202001   
...     ...         ...     ...   ...      ...      ...       ...         ...   
1862     自主        长城汽车     SUV    哈弗     哈弗H2       小型        10      201901   
1863     自主        长城汽车     SUV    哈弗     哈弗H5       紧凑        13      201901   
1864     自主        长城汽车     SUV    哈弗     哈弗H6       紧凑        13      201901   
1865     自主        长城汽车     SUV    哈弗     哈弗H8      中大型        19      201901   
1866     自主        长城汽车     SUV    哈弗     哈弗H9      中大型        24      201901   

      quantity  revenue     profit  
0         8002   264066   60735.20  
1        10535   516215   92918.70  
2        13087   536567  144873.00  
3         9133   484049   91969.30  
4         6823   245628   58950.70  
...        ...      ...        ...  
1862     17268   172680   17268.00  
1863      2298    29874    5676.06  
1864     42188   548444   98719.90  
1865      1020    19380    4845.00  
1866       928    22272    2895.36  

[1867 rows x 11 columns]

# series数据

In [22]:
#创建series(注意s为大写S)
s=pd.Series([1,2,3])
s

0    1
1    2
2    3
dtype: int64

In [23]:
type(s)

pandas.core.series.Series

In [24]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [25]:
s.values

array([1, 2, 3], dtype=int64)

In [26]:
s=pd.Series([1,2,3],index=['one','two','three'])
s

one      1
two      2
three    3
dtype: int64

In [27]:
s=pd.Series({'name':'张三','sex':'男','email':'dahsdaj@qq.com'})
s

name                 张三
sex                   男
email    dahsdaj@qq.com
dtype: object

In [28]:
s['sex']

'男'

# dataframe

In [29]:
data={
    '姓名':['张三','李四','王老五','赵六','谢谢'],
    '年龄':[20,30,40,50,60],
    '工资':[6000,6000,6000,6000,6000]
}

In [30]:
type(data)

dict

In [31]:
df=pd.DataFrame(data)
df

姓名  年龄    工资
0   张三  20  6000
1   李四  30  6000
2  王老五  40  6000
3   赵六  50  6000
4   谢谢  60  6000

In [32]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
df.values

array([['张三', 20, 6000],
       ['李四', 30, 6000],
       ['王老五', 40, 6000],
       ['赵六', 50, 6000],
       ['谢谢', 60, 6000]], dtype=object)

In [34]:
df.columns

Index(['姓名', '年龄', '工资'], dtype='object')

In [35]:
df.columns=['usernumes','age','sal']
df

usernumes  age   sal
0        张三   20  6000
1        李四   30  6000
2       王老五   40  6000
3        赵六   50  6000
4        谢谢   60  6000

## 从dataframe中查询出sries

In [36]:
filepath1='./data/saleinfo_month.xls'
df_1=pd.read_excel(filepath1)
df_1

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
0        德系        北京奔驰     SUV    奔驰    奔驰GLA       紧凑        33      202001   
1        德系        北京奔驰     SUV    奔驰    奔驰GLC       中型        49      202001   
2        德系        北京奔驰      轿车    奔驰     奔驰C级       中型        41      202001   
3        德系        北京奔驰      轿车    奔驰     奔驰E级      中大型        53      202001   
4        德系        华晨宝马     SUV    宝马     宝马X1       紧凑        36      202001   
...     ...         ...     ...   ...      ...      ...       ...         ...   
1862     自主        长城汽车     SUV    哈弗     哈弗H2       小型        10      201901   
1863     自主        长城汽车     SUV    哈弗     哈弗H5       紧凑        13      201901   
1864     自主        长城汽车     SUV    哈弗     哈弗H6       紧凑        13      201901   
1865     自主        长城汽车     SUV    哈弗     哈弗H8      中大型        19      201901   
1866     自主        长城汽车     SUV    哈弗     哈弗H9      中大型        24      201901   

      quantity  revenue     profit  
0         8002   264066   60735.20  
1        10535   516215   92918.70  
2        13087   536567  144873.00  
3         9133   484049   91969.30  
4         6823   245628   58950.70  
...        ...      ...        ...  
1862     17268   172680   17268.00  
1863      2298    29874    5676.06  
1864     42188   548444   98719.90  
1865      1020    19380    4845.00  
1866       928    22272    2895.36  

[1867 rows x 11 columns]

In [37]:
type(df_1)

pandas.core.frame.DataFrame

In [38]:
df_1[['series','brand']]

series brand
0        德系    奔驰
1        德系    奔驰
2        德系    奔驰
3        德系    奔驰
4        德系    宝马
...     ...   ...
1862     自主    哈弗
1863     自主    哈弗
1864     自主    哈弗
1865     自主    哈弗
1866     自主    哈弗

[1867 rows x 2 columns]

In [39]:
type(df_1[['series','brand']])

pandas.core.frame.DataFrame

In [40]:
df_1[['carprice']]

carprice
0           33
1           49
2           41
3           53
4           36
...        ...
1862        10
1863        13
1864        13
1865        19
1866        24

[1867 rows x 1 columns]

In [41]:
type(df_1[['carprice']])

pandas.core.frame.DataFrame

In [42]:
df_1.loc[1]

series              德系
manufacture       北京奔驰
cartype            SUV
brand               奔驰
carclass         奔驰GLC
carlevel            中型
carprice            49
stat_month      202001
quantity         10535
revenue         516215
profit         92918.7
Name: 1, dtype: object

In [43]:
type(df_1.loc[1])

pandas.core.series.Series

In [44]:
df_1.loc[3:8]

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
3     德系        北京奔驰      轿车    奔驰     奔驰E级      中大型        53      202001   
4     德系        华晨宝马     SUV    宝马     宝马X1       紧凑        36      202001   
5     德系        华晨宝马      轿车    宝马     宝马2系       紧凑        28      202001   
6     德系        华晨宝马      轿车    宝马     宝马3系       中型        39      202001   
7     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      202001   
8     德系        上汽大众     SUV    大众       途观       紧凑        26      202001   

   quantity  revenue    profit  
3      9133   484049   91969.3  
4      6823   245628   58950.7  
5      1060    29680    7420.0  
6     11477   447603   93996.6  
7     12229   745969  186492.0  
8     23538   611988  159117.0

In [45]:
type(df_1.loc[3:8])

pandas.core.frame.DataFrame

# pandas数据查询

Pandas查询数据的几种方法
1. df.loc方法,根据行、列的标签值查询
2. df.iloc方法，根据行、列的数字位置查询
3. df.where方法
4. df.query方法
.loc既能查询，又能覆盖写入，强列推荐！

# df.loc

In [46]:
df_1

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
0        德系        北京奔驰     SUV    奔驰    奔驰GLA       紧凑        33      202001   
1        德系        北京奔驰     SUV    奔驰    奔驰GLC       中型        49      202001   
2        德系        北京奔驰      轿车    奔驰     奔驰C级       中型        41      202001   
3        德系        北京奔驰      轿车    奔驰     奔驰E级      中大型        53      202001   
4        德系        华晨宝马     SUV    宝马     宝马X1       紧凑        36      202001   
...     ...         ...     ...   ...      ...      ...       ...         ...   
1862     自主        长城汽车     SUV    哈弗     哈弗H2       小型        10      201901   
1863     自主        长城汽车     SUV    哈弗     哈弗H5       紧凑        13      201901   
1864     自主        长城汽车     SUV    哈弗     哈弗H6       紧凑        13      201901   
1865     自主        长城汽车     SUV    哈弗     哈弗H8      中大型        19      201901   
1866     自主        长城汽车     SUV    哈弗     哈弗H9      中大型        24      201901   

      quantity  revenue     profit  
0         8002   264066   60735.20  
1        10535   516215   92918.70  
2        13087   536567  144873.00  
3         9133   484049   91969.30  
4         6823   245628   58950.70  
...        ...      ...        ...  
1862     17268   172680   17268.00  
1863      2298    29874    5676.06  
1864     42188   548444   98719.90  
1865      1020    19380    4845.00  
1866       928    22272    2895.36  

[1867 rows x 11 columns]

In [47]:
df_1.loc[2,'carprice']

41

In [48]:
df_1.loc[3]

series              德系
manufacture       北京奔驰
cartype             轿车
brand               奔驰
carclass          奔驰E级
carlevel           中大型
carprice            53
stat_month      202001
quantity          9133
revenue         484049
profit         91969.3
Name: 3, dtype: object

In [49]:
df_1.loc[3,['series','cartype','carprice']]

series      德系
cartype     轿车
carprice    53
Name: 3, dtype: object

In [50]:
df_1.loc[0:4,'cartype']

0    SUV
1    SUV
2     轿车
3     轿车
4    SUV
Name: cartype, dtype: object

In [51]:
df_1.loc[[1,3,5],'cartype']

1    SUV
3     轿车
5     轿车
Name: cartype, dtype: object

In [52]:
df_1.loc[[1,3,5],['cartype','carprice']]

cartype  carprice
1     SUV        49
3      轿车        53
5      轿车        28

In [53]:
#根据需求找出目标项目
#df_1.loc[条件，：]
df_1.loc[df_1['series']=='德系',:]

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
0        德系        北京奔驰     SUV    奔驰    奔驰GLA       紧凑        33      202001   
1        德系        北京奔驰     SUV    奔驰    奔驰GLC       中型        49      202001   
2        德系        北京奔驰      轿车    奔驰     奔驰C级       中型        41      202001   
3        德系        北京奔驰      轿车    奔驰     奔驰E级      中大型        53      202001   
4        德系        华晨宝马     SUV    宝马     宝马X1       紧凑        36      202001   
...     ...         ...     ...   ...      ...      ...       ...         ...   
1759     德系        一汽大众      轿车    大众       宝来       紧凑         9      201901   
1760     德系        一汽大众      轿车    大众      高尔夫       紧凑        13      201901   
1761     德系        一汽大众      轿车    大众       捷达       紧凑         8      201901   
1762     德系        一汽大众      轿车    大众       迈腾       中型        25      201901   
1763     德系        一汽大众      轿车    大众       速腾       紧凑        16      201901   

      quantity  revenue    profit  
0         8002   264066   60735.2  
1        10535   516215   92918.7  
2        13087   536567  144873.0  
3         9133   484049   91969.3  
4         6823   245628   58950.7  
...        ...      ...       ...  
1759     16848   151632   15163.2  
1760     22874   297362   41630.7  
1761     35254   282032   53586.1  
1762     17151   428775   51453.0  
1763     31253   500048  110011.0  

[356 rows x 11 columns]

In [54]:
df_1.loc[(df_1['series']=='德系')&(df_1['carprice']>=40)&(df_1['cartype']=='SUV'),:]


series manufacture cartype brand carclass carlevel  carprice  stat_month  \
1        德系        北京奔驰     SUV    奔驰    奔驰GLC       中型        49      202001   
18       德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      202001   
154      德系        北京奔驰     SUV    奔驰    奔驰GLC       中型        49      201912   
170      德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201912   
310      德系        北京奔驰     SUV    奔驰    奔驰GLC       中型        49      201911   
326      德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201911   
466      德系        北京奔驰     SUV    奔驰    奔驰GLK       中型        47      201910   
482      德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201910   
621      德系        北京奔驰     SUV    奔驰    奔驰GLK       中型        47      201909   
637      德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201909   
771      德系        北京奔驰     SUV    奔驰    奔驰GLK       中型        47      201908   
786      德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201908   
913      德系        北京奔驰     SUV    奔驰    奔驰GLK       中型        47      201907   
928      德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201907   
1057     德系        北京奔驰     SUV    奔驰    奔驰GLK       中型        47      201906   
1073     德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201906   
1199     德系        北京奔驰     SUV    奔驰    奔驰GLK       中型        47      201905   
1214     德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201905   
1339     德系        北京奔驰     SUV    奔驰    奔驰GLK       中型        47      201904   
1354     德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201904   
1478     德系        北京奔驰     SUV    奔驰    奔驰GLK       中型        47      201903   
1493     德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201903   
1612     德系        北京奔驰     SUV    奔驰    奔驰GLK       中型        47      201902   
1626     德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201902   
1740     德系        北京奔驰     SUV    奔驰    奔驰GLK       中型        47      201901   
1754     德系        一汽奥迪     SUV    奥迪     奥迪Q5       中型        46      201901   

      quantity  revenue    profit  
1        10535   516215   92918.7  
18       13087   602002  180601.0  
154      10391   509159   91648.6  
170       6998   321908   41848.0  
310       6705   328545   32854.5  
326      12592   579232  127431.0  
466       6930   325710   52113.6  
482      11176   514096   56550.6  
621       7000   329000   49350.0  
637      11534   530564  132641.0  
771       9551   448897   76312.5  
786      11371   523066  115075.0  
913       8083   379901   94975.2  
928      10849   499054  124764.0  
1057      8300   390100   58515.0  
1073      9924   456504  127821.0  
1199      7254   340938   64778.2  
1214     10708   492568   88662.2  
1339      6869   322843   35512.7  
1354     11489   528494  105699.0  
1478      4711   221417   30998.4  
1493     11840   544640  163392.0  
1612      5500   258500   51700.0  
1626      8697   400062   92014.3  
1740      6006   282282   33873.8  
1754     12275   564650  152456.0

# lambda

In [55]:
def add(x,y):
    return x+y
print(add(3,4))

7


In [56]:
add=lambda x,y:x+y
print(add(3,4))

7


In [57]:
df_1

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
0        德系        北京奔驰     SUV    奔驰    奔驰GLA       紧凑        33      202001   
1        德系        北京奔驰     SUV    奔驰    奔驰GLC       中型        49      202001   
2        德系        北京奔驰      轿车    奔驰     奔驰C级       中型        41      202001   
3        德系        北京奔驰      轿车    奔驰     奔驰E级      中大型        53      202001   
4        德系        华晨宝马     SUV    宝马     宝马X1       紧凑        36      202001   
...     ...         ...     ...   ...      ...      ...       ...         ...   
1862     自主        长城汽车     SUV    哈弗     哈弗H2       小型        10      201901   
1863     自主        长城汽车     SUV    哈弗     哈弗H5       紧凑        13      201901   
1864     自主        长城汽车     SUV    哈弗     哈弗H6       紧凑        13      201901   
1865     自主        长城汽车     SUV    哈弗     哈弗H8      中大型        19      201901   
1866     自主        长城汽车     SUV    哈弗     哈弗H9      中大型        24      201901   

      quantity  revenue     profit  
0         8002   264066   60735.20  
1        10535   516215   92918.70  
2        13087   536567  144873.00  
3         9133   484049   91969.30  
4         6823   245628   58950.70  
...        ...      ...        ...  
1862     17268   172680   17268.00  
1863      2298    29874    5676.06  
1864     42188   548444   98719.90  
1865      1020    19380    4845.00  
1866       928    22272    2895.36  

[1867 rows x 11 columns]

In [58]:
df_1.loc[lambda df_1:df_1['carprice']>60,['brand','carprice','stat_month']]

brand  carprice  stat_month
7       宝马        61      202001
160     宝马        61      201912
316     宝马        61      201911
472     宝马        61      201910
627     宝马        61      201909
777     宝马        61      201908
919     宝马        61      201907
1063    宝马        61      201906
1205    宝马        61      201905
1345    宝马        61      201904
1484    宝马        61      201903
1617    宝马        61      201902
1745    宝马        61      201901

# df.query方法

In [59]:
df_1

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
0        德系        北京奔驰     SUV    奔驰    奔驰GLA       紧凑        33      202001   
1        德系        北京奔驰     SUV    奔驰    奔驰GLC       中型        49      202001   
2        德系        北京奔驰      轿车    奔驰     奔驰C级       中型        41      202001   
3        德系        北京奔驰      轿车    奔驰     奔驰E级      中大型        53      202001   
4        德系        华晨宝马     SUV    宝马     宝马X1       紧凑        36      202001   
...     ...         ...     ...   ...      ...      ...       ...         ...   
1862     自主        长城汽车     SUV    哈弗     哈弗H2       小型        10      201901   
1863     自主        长城汽车     SUV    哈弗     哈弗H5       紧凑        13      201901   
1864     自主        长城汽车     SUV    哈弗     哈弗H6       紧凑        13      201901   
1865     自主        长城汽车     SUV    哈弗     哈弗H8      中大型        19      201901   
1866     自主        长城汽车     SUV    哈弗     哈弗H9      中大型        24      201901   

      quantity  revenue     profit  
0         8002   264066   60735.20  
1        10535   516215   92918.70  
2        13087   536567  144873.00  
3         9133   484049   91969.30  
4         6823   245628   58950.70  
...        ...      ...        ...  
1862     17268   172680   17268.00  
1863      2298    29874    5676.06  
1864     42188   548444   98719.90  
1865      1020    19380    4845.00  
1866       928    22272    2895.36  

[1867 rows x 11 columns]

In [60]:
df_1.query("carprice>60")

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
7        德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      202001   
160      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201912   
316      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201911   
472      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201910   
627      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201909   
777      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201908   
919      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201907   
1063     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201906   
1205     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201905   
1345     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201904   
1484     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201903   
1617     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201902   
1745     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201901   

      quantity  revenue    profit  
7        12229   745969  186492.0  
160       9914   604754  145141.0  
316      12912   787632  102392.0  
472      11344   691984  131477.0  
627      14907   909327  109119.0  
777      12903   787083  125933.0  
919      12190   743590  133846.0  
1063     14344   874984  122498.0  
1205     13429   819169  245751.0  
1345     12060   735660  147132.0  
1484     12445   759145  136646.0  
1617      6315   385215   57782.2  
1745     11016   671976  114236.0

In [61]:
'''
    一个或多个条件下过滤，query（）的语法都保持不变
    但是需要指定两个或多个条件进行过滤的方式
    and：回在满足两个条件的所有记录
    or：返回满足任意条件的所有记录
'''
df_1.query("brand=='宝马' and carprice>40 ")

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
7        德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      202001   
160      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201912   
316      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201911   
472      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201910   
627      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201909   
777      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201908   
919      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201907   
1063     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201906   
1205     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201905   
1345     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201904   
1484     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201903   
1617     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201902   
1745     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201901   

      quantity  revenue    profit  
7        12229   745969  186492.0  
160       9914   604754  145141.0  
316      12912   787632  102392.0  
472      11344   691984  131477.0  
627      14907   909327  109119.0  
777      12903   787083  125933.0  
919      12190   743590  133846.0  
1063     14344   874984  122498.0  
1205     13429   819169  245751.0  
1345     12060   735660  147132.0  
1484     12445   759145  136646.0  
1617      6315   385215   57782.2  
1745     11016   671976  114236.0

表示否定的词语
not关键词
!=

In [62]:
df_1.query("not(carprice<60)")

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
7        德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      202001   
160      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201912   
316      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201911   
472      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201910   
627      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201909   
777      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201908   
919      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201907   
1063     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201906   
1205     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201905   
1345     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201904   
1484     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201903   
1617     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201902   
1745     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201901   

      quantity  revenue    profit  
7        12229   745969  186492.0  
160       9914   604754  145141.0  
316      12912   787632  102392.0  
472      11344   691984  131477.0  
627      14907   909327  109119.0  
777      12903   787083  125933.0  
919      12190   743590  133846.0  
1063     14344   874984  122498.0  
1205     13429   819169  245751.0  
1345     12060   735660  147132.0  
1484     12445   759145  136646.0  
1617      6315   385215   57782.2  
1745     11016   671976  114236.0

日期时间过滤
使用query（）函数在日期时间值上进行查询的唯一要求是，包含这些值的列（一竖行）应为数据类型datatime64[ns]
示例数据中，我们看到的列是日期时间，但是我们电脑通过路径解析是字符串，所以需要对其进行转换后解析：
df["字段"]=pd.to_datetime(df["字段"],format="%Y-%m-%D")

In [63]:
fpath="./data/spider.csv"

In [64]:
df = pd.read_csv(fpath,header=None,names=
['date1','url','title','val1','val2'],usecols=['date1','url','title'])
df

date1                               url  \
0      2015-4-28           http://www.apinpai.com/   
1      2015-8-24           http://www.apinpai.com/   
2     2015-12-14         http://www.movie.com/dor/   
3       2015-4-2              http://bj.qu114.com/   
4     2015-12-19         http://www.movie.com/dor/   
...          ...                               ...   
1391   2015-7-31        http://beijing.faxinxi.cn/   
1392   2015-4-20           http://www.denghuo.com/   
1393    2015-4-2           http://www.yifawang.cn/   
1394   2015-4-15  http://www.wuhan58.com/index.php   
1395   2015-5-16          http://www.favolist.com/   

                                                  title  
0                                   采蘑菇的小姑娘;小蓓蕾组合;90;儿歌  
1                                           我;张国荣;80;励志  
2     《恶棍天使》;2015.12.24;2016.2.13;天津橙子映像传媒有限公司、北京光线影...  
3                                      my way;张敬轩;90;励志  
4     《失孤》;2015.3.20;2015.5.3;华谊兄弟传媒集团、源合圣影视、映艺娱乐;彭三...  
...                                                 ...  
1391                                     同道中人;张国荣;80;励志  
1392                                   忘记拥抱;a-lin;80;伤感  
1393                                 路...一直都在;陈奕迅;90;励志  
1394                                    像我一样骄傲;赵传;80;励志  
1395                                     最冷一天;陈奕迅;90;伤感  

[1396 rows x 3 columns]

In [65]:
df["date1"] = pd.to_datetime(df["date1"], format="%Y-%m-%d")

In [66]:
df.query("date1.dt.month == 5")

date1                           url              title
5    2015-05-28      http://www.favolist.com/        屋顶;温岚;80;励志
22   2015-05-31     http://www.alifenfen.com/   忘记拥抱;a-lin;80;伤感
29   2015-05-01          http://www.010y.com/  一起走过的日子;刘德华;80;伤感
37   2015-05-15          http://www.jieu.com/     数鸭子;少儿歌曲;90;儿歌
45   2015-05-14             http://bj.454.cn/   my way;张敬轩;90;励志
...         ...                           ...                ...
1375 2015-05-15      http://www.favolist.com/    匿名的好友;杨丞琳;90;伤感
1377 2015-05-10          http://www.010y.com/    感恩的心;欧阳菲菲;90;励志
1382 2015-05-07       http://www.qiyi123.com/   忘记拥抱;a-lin;80;伤感
1383 2015-05-17  http://beijing.hand2hand.cn/     同道中人;张国荣;80;励志
1395 2015-05-16      http://www.favolist.com/     最冷一天;陈奕迅;90;伤感

[205 rows x 3 columns]

In [67]:
df.query("date1.dt.day == 20")

date1                               url  \
25   2015-04-20          http://www.favolist.com/   
98   2015-07-20  http://www.wuhan58.com/index.php   
106  2015-04-20           http://www.apinpai.com/   
156  2015-12-20         http://www.movie.com/dor/   
167  2015-08-20                 http://bj.454.cn/   
169  2015-12-20         http://www.movie.com/dor/   
190  2015-12-20         http://www.movie.com/bor/   
217  2015-12-20         http://www.movie.com/dor/   
223  2015-06-20          http://www.favolist.com/   
271  2015-08-20           http://www.qiyi123.com/   
332  2015-07-20         http://www.alifenfen.com/   
371  2015-07-20              http://bj.qu114.com/   
372  2015-08-20             http://www.wanxn.com/   
378  2015-08-20           http://www.denghuo.com/   
423  2015-03-20        http://beijing.faxinxi.cn/   
436  2015-05-20             http://www.ezxun.com/   
462  2015-06-20  http://www.wuhan58.com/index.php   
511  2015-04-20             http://www.qudee.com/   
582  2015-05-20           http://www.mouxiao.com/   
659  2015-03-20             http://info.tianya.cn   
682  2015-06-20              http://www.jieu.com/   
705  2015-12-20         http://www.movie.com/dor/   
710  2015-06-20           http://www.yifawang.cn/   
766  2015-06-20      http://beijing.hand2hand.cn/   
780  2015-07-20                 http://bj.454.cn/   
847  2015-04-20              http://bj.qu114.com/   
852  2015-08-20             http://www.waaku.com/   
898  2015-08-20             http://www.wanxn.com/   
902  2015-05-20           http://www.qiyi123.com/   
969  2015-12-20   http://www.movie.com/bor/12386／   
1019 2015-06-20        http://beijing.faxinxi.cn/   
1095 2015-07-20           http://www.apinpai.com/   
1097 2015-04-20             http://www.ezxun.com/   
1113 2015-05-20              http://www.010y.com/   
1119 2015-08-20             http://www.99inf.com/   
1190 2015-03-20             http://www.qudee.com/   
1216 2015-03-20         http://www.alifenfen.com/   
1257 2015-06-20           http://www.qiyi123.com/   
1260 2015-04-20           http://www.yifawang.cn/   
1336 2015-12-20         http://www.movie.com/bor/   
1346 2015-07-20           http://www.apinpai.com/   
1363 2015-05-20          http://www.favolist.com/   
1381 2015-06-20        http://beijing.faxinxi.cn/   
1390 2015-07-20             http://www.ezxun.com/   
1392 2015-04-20           http://www.denghuo.com/   

                                                  title  
25                      story of my life;bon jovi;90;励志  
98                                      感恩的心;欧阳菲菲;90;励志  
106                                   一起走过的日子;刘德华;80;伤感  
156   《百团大战》;2015.8.28;2015.10.11;八一电影制片厂；中国电影股份有限公司...  
167                                  无悔这一生;beyond;80;励志  
169   《简单爱》;2015.7.3;2015.7.19;中视合利（北京）文化投资有限公司一鸣影业公...  
190   《闯入者》;2015.4.30;2015.5.24;冬春文化、银润传媒、合润传媒、安乐电影、...  
217   《将错就错》;2015.3.5;2015.3.29;中国电影股份有限公司等;王宁;小沈阳，田...  
223                                   一起走过的日子;刘德华;80;伤感  
271                              加油;林俊杰/mc hotdog;90;励志  
332                                         星;邓丽君;80;励志  
371                                        借我;谢春花;90;伤感  
372                                      壮志雄心;李克勤;90;励志  
378                                        空壳;陈慧敏;90;伤感  
423                                      我心是海洋;蔡琴;80;励志  
436                                     匿名的好友;杨丞琳;90;伤感  
462                                      太阳星辰;张学友;80;励志  
511                                    爱让世界更美;童安格;90;励志  
582                                 采蘑菇的小姑娘;小蓓蕾组合;90;儿歌  
659                                        借过;容祖儿;90;伤感  
682                                来来回回;陈楚生&spy.c;90;伤感  
705   《浪漫天降》;2015.10.23;2015.11.8;;宁瀛;夏雨，关晓彤，邱泽;浪漫，爱...  
710                                         我;张国荣;80;励志  
766                                      太阳星辰;张学友;80;励志  
780                                   光辉岁月;beyond;80;励志  
847                                         屋顶;温岚;80;励志  
852  

# pandas怎样新增数列

1.直接赋值
2.df.apply方法
3.df.assign方法
4.按条件选择分组分别赋值

# 直接赋值

In [68]:
#示例，清理温度列，变成数字类型
import pandas as pd
df=pd.read_csv("./data/beijing_tianqi_2018.csv")
df

ymd bWendu yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel
0    2018-01-01     3℃    -6℃   晴~多云       东北风   1-2级   59       良         2
1    2018-01-02     2℃    -5℃   阴~多云       东北风   1-2级   49       优         1
2    2018-01-03     2℃    -5℃     多云        北风   1-2级   28       优         1
3    2018-01-04     0℃    -8℃      阴       东北风   1-2级   28       优         1
4    2018-01-05     3℃    -6℃   多云~晴       西北风   1-2级   50       优         1
..          ...    ...    ...    ...       ...    ...  ...     ...       ...
360  2018-12-27    -5℃   -12℃   多云~晴       西北风     3级   48       优         1
361  2018-12-28    -3℃   -11℃      晴       西北风     3级   40       优         1
362  2018-12-29    -3℃   -12℃      晴       西北风     2级   29       优         1
363  2018-12-30    -2℃   -11℃   晴~多云       东北风     1级   31       优         1
364  2018-12-31    -2℃   -10℃     多云       东北风     1级   56       良         2

[365 rows x 9 columns]

In [69]:
#清除后缀℃
df.loc[:,"bWendu"]=df["bWendu"].str.replace("℃","").astype('int32')
df.loc[:,"yWendu"]=df["yWendu"].str.replace("℃","").astype('int32')
df

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel
0    2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良         2
1    2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优         1
2    2018-01-03       2      -5     多云        北风   1-2级   28       优         1
3    2018-01-04       0      -8      阴       东北风   1-2级   28       优         1
4    2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优         1
..          ...     ...     ...    ...       ...    ...  ...     ...       ...
360  2018-12-27      -5     -12   多云~晴       西北风     3级   48       优         1
361  2018-12-28      -3     -11      晴       西北风     3级   40       优         1
362  2018-12-29      -3     -12      晴       西北风     2级   29       优         1
363  2018-12-30      -2     -11   晴~多云       东北风     1级   31       优         1
364  2018-12-31      -2     -10     多云       东北风     1级   56       良         2

[365 rows x 9 columns]

In [70]:
#计算温差
df.loc[:,"Wencha"]=df["bWendu"]-df["yWendu"]
df

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  \
0    2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良   
1    2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优   
2    2018-01-03       2      -5     多云        北风   1-2级   28       优   
3    2018-01-04       0      -8      阴       东北风   1-2级   28       优   
4    2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优   
..          ...     ...     ...    ...       ...    ...  ...     ...   
360  2018-12-27      -5     -12   多云~晴       西北风     3级   48       优   
361  2018-12-28      -3     -11      晴       西北风     3级   40       优   
362  2018-12-29      -3     -12      晴       西北风     2级   29       优   
363  2018-12-30      -2     -11   晴~多云       东北风     1级   31       优   
364  2018-12-31      -2     -10     多云       东北风     1级   56       良   

     aqiLevel  Wencha  
0           2       9  
1           1       7  
2           1       7  
3           1       8  
4           1       9  
..        ...     ...  
360         1       7  
361         1       8  
362         1       9  
363         1       9  
364         2       8  

[365 rows x 10 columns]

In [71]:
df.head()

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel  \
0  2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良         2   
1  2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优         1   
2  2018-01-03       2      -5     多云        北风   1-2级   28       优         1   
3  2018-01-04       0      -8      阴       东北风   1-2级   28       优         1   
4  2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优         1   

   Wencha  
0       9  
1       7  
2       7  
3       8  
4       9

# df.apply方法

实例：添加一列温度类型：
1. 如果最高温度大于33度就是高温
2. 低于-10度是低温
3. 否则是常温

In [72]:
#添加一个判断函数
def get_wendu_type(x):
    if x["bWendu"]>33:
        return '高温'
    if x["yWendu"]<-10:
        return '低温'
    return '常温'

In [73]:
df.loc[:,"wendu_type"]=df.apply(get_wendu_type,axis=1)
df

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  \
0    2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良   
1    2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优   
2    2018-01-03       2      -5     多云        北风   1-2级   28       优   
3    2018-01-04       0      -8      阴       东北风   1-2级   28       优   
4    2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优   
..          ...     ...     ...    ...       ...    ...  ...     ...   
360  2018-12-27      -5     -12   多云~晴       西北风     3级   48       优   
361  2018-12-28      -3     -11      晴       西北风     3级   40       优   
362  2018-12-29      -3     -12      晴       西北风     2级   29       优   
363  2018-12-30      -2     -11   晴~多云       东北风     1级   31       优   
364  2018-12-31      -2     -10     多云       东北风     1级   56       良   

     aqiLevel  Wencha wendu_type  
0           2       9         常温  
1           1       7         常温  
2           1       7         常温  
3           1       8         常温  
4           1       9         常温  
..        ...     ...        ...  
360         1       7         低温  
361         1       8         低温  
362         1       9         低温  
363         1       9         低温  
364         2       8         常温  

[365 rows x 11 columns]

# df.assign方法

In [74]:
df.assign(
    yWendu_huashi=lambda x:x["yWendu"]*9/5+32,
    bWendu_huashi=lambda x:x["bWendu"]*9/5+32
)

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  \
0    2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良   
1    2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优   
2    2018-01-03       2      -5     多云        北风   1-2级   28       优   
3    2018-01-04       0      -8      阴       东北风   1-2级   28       优   
4    2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优   
..          ...     ...     ...    ...       ...    ...  ...     ...   
360  2018-12-27      -5     -12   多云~晴       西北风     3级   48       优   
361  2018-12-28      -3     -11      晴       西北风     3级   40       优   
362  2018-12-29      -3     -12      晴       西北风     2级   29       优   
363  2018-12-30      -2     -11   晴~多云       东北风     1级   31       优   
364  2018-12-31      -2     -10     多云       东北风     1级   56       良   

     aqiLevel  Wencha wendu_type  yWendu_huashi  bWendu_huashi  
0           2       9         常温           21.2           37.4  
1           1       7         常温           23.0           35.6  
2           1       7         常温           23.0           35.6  
3           1       8         常温           17.6           32.0  
4           1       9         常温           21.2           37.4  
..        ...     ...        ...            ...            ...  
360         1       7         低温           10.4           23.0  
361         1       8         低温           12.2           26.6  
362         1       9         低温           10.4           26.6  
363         1       9         低温           12.2           28.4  
364         2       8         常温           14.0           28.4  

[365 rows x 13 columns]

# 按条件选择分组分别赋值

In [75]:
df['wencha_type']=''
df

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  \
0    2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良   
1    2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优   
2    2018-01-03       2      -5     多云        北风   1-2级   28       优   
3    2018-01-04       0      -8      阴       东北风   1-2级   28       优   
4    2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优   
..          ...     ...     ...    ...       ...    ...  ...     ...   
360  2018-12-27      -5     -12   多云~晴       西北风     3级   48       优   
361  2018-12-28      -3     -11      晴       西北风     3级   40       优   
362  2018-12-29      -3     -12      晴       西北风     2级   29       优   
363  2018-12-30      -2     -11   晴~多云       东北风     1级   31       优   
364  2018-12-31      -2     -10     多云       东北风     1级   56       良   

     aqiLevel  Wencha wendu_type wencha_type  
0           2       9         常温              
1           1       7         常温              
2           1       7         常温              
3           1       8         常温              
4           1       9         常温              
..        ...     ...        ...         ...  
360         1       7         低温              
361         1       8         低温              
362         1       9         低温              
363         1       9         低温              
364         2       8         常温              

[365 rows x 12 columns]

In [76]:
df.loc[df["bWendu"]-df["yWendu"]>10,"wencha_type"]="温差大"
df.loc[df["bWendu"]-df["yWendu"]<=10,"wencha_type"]="温差小"
df

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  \
0    2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良   
1    2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优   
2    2018-01-03       2      -5     多云        北风   1-2级   28       优   
3    2018-01-04       0      -8      阴       东北风   1-2级   28       优   
4    2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优   
..          ...     ...     ...    ...       ...    ...  ...     ...   
360  2018-12-27      -5     -12   多云~晴       西北风     3级   48       优   
361  2018-12-28      -3     -11      晴       西北风     3级   40       优   
362  2018-12-29      -3     -12      晴       西北风     2级   29       优   
363  2018-12-30      -2     -11   晴~多云       东北风     1级   31       优   
364  2018-12-31      -2     -10     多云       东北风     1级   56       良   

     aqiLevel  Wencha wendu_type wencha_type  
0           2       9         常温         温差小  
1           1       7         常温         温差小  
2           1       7         常温         温差小  
3           1       8         常温         温差小  
4           1       9         常温         温差小  
..        ...     ...        ...         ...  
360         1       7         低温         温差小  
361         1       8         低温         温差小  
362         1       9         低温         温差小  
363         1       9         低温         温差小  
364         2       8         常温         温差小  

[365 rows x 12 columns]

In [77]:
df["wencha_type"].value_counts()

温差小    187
温差大    178
Name: wencha_type, dtype: int64

# pandas数据统计函数

1.汇总类统计
2.唯一去重和按值计数
3.相关系数和协方差

In [78]:
#汇总
df.describe()

bWendu      yWendu         aqi    aqiLevel      Wencha
count  365.000000  365.000000  365.000000  365.000000  365.000000
mean    18.665753    8.358904   82.183562    2.090411   10.306849
std     11.858046   11.755053   51.936159    1.029798    2.781233
min     -5.000000  -12.000000   21.000000    1.000000    2.000000
25%      8.000000   -3.000000   46.000000    1.000000    8.000000
50%     21.000000    8.000000   69.000000    2.000000   10.000000
75%     29.000000   19.000000  104.000000    3.000000   12.000000
max     38.000000   27.000000  387.000000    6.000000   18.000000

In [79]:
df['bWendu'].max()

38

In [80]:
df.loc[:,'bWendu'].min()

-5

In [81]:
df['bWendu'].mean()
#平均值

18.665753424657535

In [82]:
df['bWendu'].std()
#标准差

11.858045666421837

唯一去重和按值计算

In [83]:
#唯一去重
df['fengxiang'].unique()

array(['东北风', '北风', '西北风', '西南风', '南风', '东南风', '东风', '西风'], dtype=object)

In [84]:
df['tianqi'].unique()

array(['晴~多云', '阴~多云', '多云', '阴', '多云~晴', '多云~阴', '晴', '阴~小雪', '小雪~多云',
       '小雨~阴', '小雨~雨夹雪', '多云~小雨', '小雨~多云', '大雨~小雨', '小雨', '阴~小雨',
       '多云~雷阵雨', '雷阵雨~多云', '阴~雷阵雨', '雷阵雨', '雷阵雨~大雨', '中雨~雷阵雨', '小雨~大雨',
       '暴雨~雷阵雨', '雷阵雨~中雨', '小雨~雷阵雨', '雷阵雨~阴', '中雨~小雨', '小雨~中雨', '雾~多云',
       '霾'], dtype=object)

In [85]:
df['fengli'].unique()

array(['1-2级', '4-5级', '3-4级', '2级', '1级', '3级'], dtype=object)

In [86]:
#按值计数
df['fengli'].value_counts()

1-2级    236
3-4级     68
1级       21
4-5级     20
2级       13
3级        7
Name: fengli, dtype: int64

In [87]:
df['tianqi'].value_counts()

晴         101
多云         95
多云~晴       40
晴~多云       34
多云~雷阵雨     14
多云~阴       10
雷阵雨         8
小雨~多云       8
阴~多云        8
雷阵雨~多云      7
小雨          6
多云~小雨       5
阴           4
雷阵雨~中雨      4
中雨~小雨       2
中雨~雷阵雨      2
阴~小雨        2
霾           2
大雨~小雨       1
阴~雷阵雨       1
小雨~雨夹雪      1
雷阵雨~大雨      1
小雨~阴        1
小雨~大雨       1
暴雨~雷阵雨      1
小雪~多云       1
小雨~雷阵雨      1
雷阵雨~阴       1
阴~小雪        1
小雨~中雨       1
雾~多云        1
Name: tianqi, dtype: int64

相关系数和协方差
用途（超级厉害）
1. 两只股票，是不是同涨同跌？程度多大？正相关还是负相关？
2. 产品销量的波动，跟哪些因素正相关、负相关，程度有多大？
来自知乎，对于两个变量x、y:
3. 协方差：衡量同向反向程度，如果协方差为正，说明x,y同向变化，协方差越大说明同向程度越高;
如果协方差为负，说明x,y反向运动，协方差越小说明反向程度越高
4. 相关系数： 衡量相似度程度，当他们的相关系数为1时，说明两个变量变化时的正向相似度最大，
当相关系数为-1时，说明两个变量变化的反向相似度最大

In [88]:
#协方差矩阵
df.cov()
#如aqiLevel空气指数等级与其他bWendu,yWendu,wencha的协方差不大，但为正，说明正相关，但影
#响不大

bWendu      yWendu          aqi   aqiLevel     Wencha
bWendu    140.613247  135.529633    47.462622   0.879204   5.083614
yWendu    135.529633  138.181274    16.186685   0.264165  -2.651641
aqi        47.462622   16.186685  2697.364564  50.749842  31.275937
aqiLevel    0.879204    0.264165    50.749842   1.060485   0.615038
Wencha      5.083614   -2.651641    31.275937   0.615038   7.735255

In [89]:
#相关系数矩阵
df.corr()
#如aqi空间指数与bWendu和yWendu相关系数小，说明相关影响不大，但与aqiLevel相关系数大，因为
#他们一定有运算关系，影响较大

bWendu    yWendu       aqi  aqiLevel    Wencha
bWendu    1.000000  0.972292  0.077067  0.071999  0.154142
yWendu    0.972292  1.000000  0.026513  0.021822 -0.081106
aqi       0.077067  0.026513  1.000000  0.948883  0.216523
aqiLevel  0.071999  0.021822  0.948883  1.000000  0.214740
Wencha    0.154142 -0.081106  0.216523  0.214740  1.000000

In [90]:
df["aqi"].corr(df["bWendu"])

0.07706705916811069

# 缺失值处理

In [91]:
#检测是否为空
studf=pd.read_excel("./data/缼失值处理.xlsx",skiprows=2)
#跳过前两行
studf

Unnamed: 0   姓名   科目    分数
0          NaN   小明   语文  85.0
1          NaN  NaN   数学  80.0
2          NaN  NaN   英语  90.0
3          NaN  NaN  NaN   NaN
4          NaN   小王   语文  85.0
5          NaN  NaN   数学   NaN
6          NaN  NaN   英语  90.0
7          NaN  NaN  NaN   NaN
8          NaN   小刚   语文  85.0
9          NaN  NaN   数学  80.0
10         NaN  NaN   英语  90.0

In [92]:
#检测空值
studf.isnull()

Unnamed: 0     姓名     科目     分数
0         True  False  False  False
1         True   True  False  False
2         True   True  False  False
3         True   True   True   True
4         True  False  False  False
5         True   True  False   True
6         True   True  False  False
7         True   True   True   True
8         True  False  False  False
9         True   True  False  False
10        True   True  False  False

In [93]:
#检测某一列
studf["分数"].isnull()

0     False
1     False
2     False
3      True
4     False
5      True
6     False
7      True
8     False
9     False
10    False
Name: 分数, dtype: bool

In [94]:
studf["分数"].notnull()

0      True
1      True
2      True
3     False
4      True
5     False
6      True
7     False
8      True
9      True
10     True
Name: 分数, dtype: bool

In [95]:
#筛选没有空分数的所有行
studf.loc[studf["分数"].notnull(),:]

Unnamed: 0   姓名  科目    分数
0          NaN   小明  语文  85.0
1          NaN  NaN  数学  80.0
2          NaN  NaN  英语  90.0
4          NaN   小王  语文  85.0
6          NaN  NaN  英语  90.0
8          NaN   小刚  语文  85.0
9          NaN  NaN  数学  80.0
10         NaN  NaN  英语  90.0

In [96]:
studf.loc[~studf["分数"].notnull(),:]

Unnamed: 0   姓名   科目  分数
3         NaN  NaN  NaN NaN
5         NaN  NaN   数学 NaN
7         NaN  NaN  NaN NaN

# 删除全是空的列

In [97]:
studf.dropna(axis='columns',how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [98]:
studf.dropna(axis='columns',how='all')

姓名   科目    分数
0    小明   语文  85.0
1   NaN   数学  80.0
2   NaN   英语  90.0
3   NaN  NaN   NaN
4    小王   语文  85.0
5   NaN   数学   NaN
6   NaN   英语  90.0
7   NaN  NaN   NaN
8    小刚   语文  85.0
9   NaN   数学  80.0
10  NaN   英语  90.0

In [99]:
studf

Unnamed: 0   姓名   科目    分数
0          NaN   小明   语文  85.0
1          NaN  NaN   数学  80.0
2          NaN  NaN   英语  90.0
3          NaN  NaN  NaN   NaN
4          NaN   小王   语文  85.0
5          NaN  NaN   数学   NaN
6          NaN  NaN   英语  90.0
7          NaN  NaN  NaN   NaN
8          NaN   小刚   语文  85.0
9          NaN  NaN   数学  80.0
10         NaN  NaN   英语  90.0

In [100]:
studf.dropna(axis='columns',how='all',inplace=True)

In [101]:
studf

姓名   科目    分数
0    小明   语文  85.0
1   NaN   数学  80.0
2   NaN   英语  90.0
3   NaN  NaN   NaN
4    小王   语文  85.0
5   NaN   数学   NaN
6   NaN   英语  90.0
7   NaN  NaN   NaN
8    小刚   语文  85.0
9   NaN   数学  80.0
10  NaN   英语  90.0

In [102]:
studf.dropna(axis='index',how='all',inplace=True)
#删除都为空的行

In [103]:
studf

姓名  科目    分数
0    小明  语文  85.0
1   NaN  数学  80.0
2   NaN  英语  90.0
4    小王  语文  85.0
5   NaN  数学   NaN
6   NaN  英语  90.0
8    小刚  语文  85.0
9   NaN  数学  80.0
10  NaN  英语  90.0

In [104]:
studf.fillna({"分数":0})

姓名  科目    分数
0    小明  语文  85.0
1   NaN  数学  80.0
2   NaN  英语  90.0
4    小王  语文  85.0
5   NaN  数学   0.0
6   NaN  英语  90.0
8    小刚  语文  85.0
9   NaN  数学  80.0
10  NaN  英语  90.0

In [105]:
studf

姓名  科目    分数
0    小明  语文  85.0
1   NaN  数学  80.0
2   NaN  英语  90.0
4    小王  语文  85.0
5   NaN  数学   NaN
6   NaN  英语  90.0
8    小刚  语文  85.0
9   NaN  数学  80.0
10  NaN  英语  90.0

In [106]:
studf.loc[:,'分数']=studf['分数'].fillna(0)

In [107]:
studf

姓名  科目    分数
0    小明  语文  85.0
1   NaN  数学  80.0
2   NaN  英语  90.0
4    小王  语文  85.0
5   NaN  数学   0.0
6   NaN  英语  90.0
8    小刚  语文  85.0
9   NaN  数学  80.0
10  NaN  英语  90.0

In [108]:
studf.loc[:,'姓名']=studf['姓名'].fillna(method="ffill")

In [109]:
studf

姓名  科目    分数
0   小明  语文  85.0
1   小明  数学  80.0
2   小明  英语  90.0
4   小王  语文  85.0
5   小王  数学   0.0
6   小王  英语  90.0
8   小刚  语文  85.0
9   小刚  数学  80.0
10  小刚  英语  90.0

In [110]:
studf

姓名  科目    分数
0   小明  语文  85.0
1   小明  数学  80.0
2   小明  英语  90.0
4   小王  语文  85.0
5   小王  数学   0.0
6   小王  英语  90.0
8   小刚  语文  85.0
9   小刚  数学  80.0
10  小刚  英语  90.0

In [111]:
studf.to_excel('./data/shuchu.xlsx',index=False)
#输出保存，index=false指的是不输出索引值在文件中

In [112]:
studf.to_csv('./data/shuchu1.csv',index=False)
#输出一个csv文件

# pandas数据排序

In [113]:
import pandas as pd
filepath1='./data/saleinfo_month.xls'
che=pd.read_excel(filepath1)
che

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
0        德系        北京奔驰     SUV    奔驰    奔驰GLA       紧凑        33      202001   
1        德系        北京奔驰     SUV    奔驰    奔驰GLC       中型        49      202001   
2        德系        北京奔驰      轿车    奔驰     奔驰C级       中型        41      202001   
3        德系        北京奔驰      轿车    奔驰     奔驰E级      中大型        53      202001   
4        德系        华晨宝马     SUV    宝马     宝马X1       紧凑        36      202001   
...     ...         ...     ...   ...      ...      ...       ...         ...   
1862     自主        长城汽车     SUV    哈弗     哈弗H2       小型        10      201901   
1863     自主        长城汽车     SUV    哈弗     哈弗H5       紧凑        13      201901   
1864     自主        长城汽车     SUV    哈弗     哈弗H6       紧凑        13      201901   
1865     自主        长城汽车     SUV    哈弗     哈弗H8      中大型        19      201901   
1866     自主        长城汽车     SUV    哈弗     哈弗H9      中大型        24      201901   

      quantity  revenue     profit  
0         8002   264066   60735.20  
1        10535   516215   92918.70  
2        13087   536567  144873.00  
3         9133   484049   91969.30  
4         6823   245628   58950.70  
...        ...      ...        ...  
1862     17268   172680   17268.00  
1863      2298    29874    5676.06  
1864     42188   548444   98719.90  
1865      1020    19380    4845.00  
1866       928    22272    2895.36  

[1867 rows x 11 columns]

In [114]:
che["carprice"].sort_values().head(5)

1037    4
426     4
750     4
755     4
1023    4
Name: carprice, dtype: int64

In [115]:
che["carprice"].value_counts()

9     188
13    157
11    147
14    128
10    121
12     87
15     77
8      76
16     75
21     68
17     62
7      54
23     48
20     39
22     39
24     39
6      39
33     39
30     39
19     37
28     37
18     34
4      31
25     26
36     26
50     18
29     14
58     13
35     13
41     13
53     13
61     13
39     13
26     13
46     13
47     10
27      5
49      3
Name: carprice, dtype: int64

In [116]:
che["carprice"].sort_values(ascending=False)

1745    61
1205    61
1345    61
919     61
1484    61
        ..
733      4
1320     4
1166     4
445      4
114      4
Name: carprice, Length: 1867, dtype: int64

In [117]:
che["carprice"].sort_values()

1037     4
426      4
750      4
755      4
1023     4
        ..
777     61
1745    61
1345    61
7       61
316     61
Name: carprice, Length: 1867, dtype: int64

In [118]:
che["carprice"].value_counts().head(6)

9     188
13    157
11    147
14    128
10    121
12     87
Name: carprice, dtype: int64

# dataframe排序

In [119]:
che.sort_values(by='revenue')

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
139      自主      上汽通用五菱      轿车    宝骏    宝骏630       紧凑         7      202001   
946      日系        东风本田      轿车    本田       思域       紧凑        14      201903   
711      日系        广汽本田     SUV    本田       冠道       中型        27      201909   
58       韩系      东风悦达起亚      轿车    起亚      福瑞迪       紧凑        11      202001   
1342     德系        华晨宝马     SUV    宝马     宝马X1       紧凑        36      201904   
...     ...         ...     ...   ...      ...      ...       ...         ...   
213      美系        上汽通用     SUV    别克      昂科威       紧凑        28      201912   
525      美系        上汽通用     SUV    别克      昂科威       紧凑        28      201910   
627      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201909   
461      自主        长城汽车     SUV    哈弗     哈弗H6       紧凑        13      201911   
305      自主        长城汽车     SUV    哈弗     哈弗H6       紧凑        13      201912   

      quantity  revenue     profit  
139         15      105      23.10  
946         10      140      22.40  
711         11      297      59.40  
58          29      319      95.70  
1342        12      432      69.12  
...        ...      ...        ...  
213      31749   888972  151125.00  
525      32296   904288  217029.00  
627      14907   909327  109119.00  
461      70292   913796  182759.00  
305      80495  1046440  251144.00  

[1867 rows x 11 columns]

In [120]:
che.sort_values(by='carprice')

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
1037     自主        奇瑞汽车      轿车    奇瑞       QQ       紧凑         4      201907   
426      自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      201911   
750      自主        奇瑞汽车      轿车    奇瑞       QQ       紧凑         4      201909   
755      自主      上汽通用五菱      轿车    宝骏    宝骏310       小型         4      201909   
1023     自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      201907   
...     ...         ...     ...   ...      ...      ...       ...         ...   
777      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201908   
1745     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201901   
1345     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201904   
7        德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      202001   
316      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201911   

      quantity  revenue     profit  
1037       584     2336     256.96  
426       1076     4304     989.92  
750        628     2512     301.44  
755       5310    21240    2336.40  
1023       345     1380     345.00  
...        ...      ...        ...  
777      12903   787083  125933.00  
1745     11016   671976  114236.00  
1345     12060   735660  147132.00  
7        12229   745969  186492.00  
316      12912   787632  102392.00  

[1867 rows x 11 columns]

In [121]:
che.sort_values(by='carprice',ascending=False)

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
1745     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201901   
1205     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201905   
1345     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201904   
919      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201907   
1484     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201903   
...     ...         ...     ...   ...      ...      ...       ...         ...   
733      自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      201909   
1320     自主        奇瑞汽车      轿车    奇瑞       QQ       紧凑         4      201905   
1166     自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      201906   
445      自主        奇瑞汽车      轿车    奇瑞       QQ       紧凑         4      201911   
114      自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      202001   

      quantity  revenue     profit  
1745     11016   671976  114236.00  
1205     13429   819169  245751.00  
1345     12060   735660  147132.00  
919      12190   743590  133846.00  
1484     12445   759145  136646.00  
...        ...      ...        ...  
733        849     3396     815.04  
1320      2060     8240    1400.80  
1166       968     3872     503.36  
445       1569     6276    1820.04  
114        829     3316     895.32  

[1867 rows x 11 columns]

In [122]:
che.sort_values(by=['carprice','revenue'])

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
1023     自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      201907   
582      自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      201910   
1037     自主        奇瑞汽车      轿车    奇瑞       QQ       紧凑         4      201907   
1713     自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      201902   
750      自主        奇瑞汽车      轿车    奇瑞       QQ       紧凑         4      201909   
...     ...         ...     ...   ...      ...      ...       ...         ...   
777      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201908   
316      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201911   
1205     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201905   
1063     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201906   
627      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201909   

      quantity  revenue     profit  
1023       345     1380     345.00  
582        539     2156     603.68  
1037       584     2336     256.96  
1713       598     2392     454.48  
750        628     2512     301.44  
...        ...      ...        ...  
777      12903   787083  125933.00  
316      12912   787632  102392.00  
1205     13429   819169  245751.00  
1063     14344   874984  122498.00  
627      14907   909327  109119.00  

[1867 rows x 11 columns]

In [123]:
che.sort_values(by=['carprice','revenue'],ascending=False)

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
627      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201909   
1063     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201906   
1205     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201905   
316      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201911   
777      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201908   
...     ...         ...     ...   ...      ...      ...       ...         ...   
750      自主        奇瑞汽车      轿车    奇瑞       QQ       紧凑         4      201909   
1713     自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      201902   
1037     自主        奇瑞汽车      轿车    奇瑞       QQ       紧凑         4      201907   
582      自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      201910   
1023     自主       比亚迪汽车      轿车   比亚迪       F0       微型         4      201907   

      quantity  revenue     profit  
627      14907   909327  109119.00  
1063     14344   874984  122498.00  
1205     13429   819169  245751.00  
316      12912   787632  102392.00  
777      12903   787083  125933.00  
...        ...      ...        ...  
750        628     2512     301.44  
1713       598     2392     454.48  
1037       584     2336     256.96  
582        539     2156     603.68  
1023       345     1380     345.00  

[1867 rows x 11 columns]

In [124]:
che.sort_values(by=['carprice','revenue'],ascending=[False,True])
#carprice和revenue有主从关系，谁在前先看谁

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
1617     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201902   
160      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201912   
1745     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201901   
472      德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201910   
1345     德系        华晨宝马      轿车    宝马     宝马5系      中大型        61      201904   
...     ...         ...     ...   ...      ...      ...       ...         ...   
755      自主      上汽通用五菱      轿车    宝骏    宝骏310       小型         4      201909   
605      自主      上汽通用五菱      轿车    宝骏    宝骏310       小型         4      201910   
450      自主      上汽通用五菱      轿车    宝骏    宝骏310       小型         4      201911   
294      自主      上汽通用五菱      轿车    宝骏    宝骏310       小型         4      201912   
138      自主      上汽通用五菱      轿车    宝骏    宝骏310       小型         4      202001   

      quantity  revenue    profit  
1617      6315   385215   57782.2  
160       9914   604754  145141.0  
1745     11016   671976  114236.0  
472      11344   691984  131477.0  
1345     12060   735660  147132.0  
...        ...      ...       ...  
755       5310    21240    2336.4  
605      11809    47236    9447.2  
450      15006    60024   15006.0  
294      17896    71584   12169.3  
138      18006    72024   15845.3  

[1867 rows x 11 columns]

In [125]:
che.tail(3)
#后三条

series manufacture cartype brand carclass carlevel  carprice  stat_month  \
1864     自主        长城汽车     SUV    哈弗     哈弗H6       紧凑        13      201901   
1865     自主        长城汽车     SUV    哈弗     哈弗H8      中大型        19      201901   
1866     自主        长城汽车     SUV    哈弗     哈弗H9      中大型        24      201901   

      quantity  revenue    profit  
1864     42188   548444  98719.90  
1865      1020    19380   4845.00  
1866       928    22272   2895.36

# pandas字符串处理

In [126]:
import pandas as pd
t=pd.read_csv("./data/beijing_tianqi_2018.csv")
t.loc[:,"bWendu"]=t["bWendu"].str.replace("℃","").astype('int32')
t.loc[:,"yWendu"]=t["yWendu"].str.replace("℃","").astype('int32')
t

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel
0    2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良         2
1    2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优         1
2    2018-01-03       2      -5     多云        北风   1-2级   28       优         1
3    2018-01-04       0      -8      阴       东北风   1-2级   28       优         1
4    2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优         1
..          ...     ...     ...    ...       ...    ...  ...     ...       ...
360  2018-12-27      -5     -12   多云~晴       西北风     3级   48       优         1
361  2018-12-28      -3     -11      晴       西北风     3级   40       优         1
362  2018-12-29      -3     -12      晴       西北风     2级   29       优         1
363  2018-12-30      -2     -11   晴~多云       东北风     1级   31       优         1
364  2018-12-31      -2     -10     多云       东北风     1级   56       良         2

[365 rows x 9 columns]

In [127]:
t.dtypes

ymd          object
bWendu        int32
yWendu        int32
tianqi       object
fengxiang    object
fengli       object
aqi           int64
aqiInfo      object
aqiLevel      int64
dtype: object

In [128]:
t["tianqi"].str.len()

0      4
1      4
2      2
3      1
4      4
      ..
360    4
361    1
362    1
363    4
364    2
Name: tianqi, Length: 365, dtype: int64

In [129]:
#设一个条件
condition=t["ymd"].str.startswith("2018-02")

In [130]:
condition

0      False
1      False
2      False
3      False
4      False
       ...  
360    False
361    False
362    False
363    False
364    False
Name: ymd, Length: 365, dtype: bool

In [131]:
t[condition]

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel
31  2018-02-01       4      -7     多云        北风   1-2级   68       良         2
32  2018-02-02      -1      -9      晴        北风   3-4级   32       优         1
33  2018-02-03       0      -9     多云        北风   1-2级   24       优         1
34  2018-02-04       1      -8      晴       西南风   1-2级   36       优         1
35  2018-02-05       0     -10      晴        北风   3-4级   24       优         1
36  2018-02-06       3      -7   多云~阴       西南风   1-2级   56       良         2
37  2018-02-07       2     -10   多云~晴        北风   4-5级   63       良         2
38  2018-02-08       3      -7     多云        南风   3-4级   67       良         2
39  2018-02-09       4      -9     多云       西北风   4-5级   93       良         2
40  2018-02-10       1      -9      晴       西北风   3-4级   39       优         1
41  2018-02-11       0      -9      晴       西北风   4-5级   62       良         2
42  2018-02-12       5      -7      晴       西北风   1-2级   53       良         2
43  2018-02-13       8      -4   晴~多云        西风   1-2级   78       良         2
44  2018-02-14       6      -6     多云        北风   1-2级   42       优         1
45  2018-02-15       5      -5     多云       西南风   1-2级   48       优         1
46  2018-02-16       8      -5   晴~多云       西南风   1-2级  118    轻度污染         3
47  2018-02-17       5      -4   多云~阴        南风   1-2级  103    轻度污染         3
48  2018-02-18       8      -3     多云        南风   1-2级  148    轻度污染         3
49  2018-02-19       6      -3     多云        南风   1-2级  183    中度污染         4
50  2018-02-20       5      -5      晴        北风   1-2级   76       良         2
51  2018-02-21       8      -4      晴        南风   1-2级   53       良         2
52  2018-02-22       9      -4     多云       西南风   1-2级   42       优         1
53  2018-02-23      10      -4     多云       东北风   1-2级   45       优         1
54  2018-02-24       3      -6   多云~晴        南风   1-2级   66       良         2
55  2018-02-25       6      -4     多云       西南风   1-2级   73       良         2
56  2018-02-26      12      -1   晴~多云       西南风   1-2级  157    中度污染         4
57  2018-02-27       7       0      阴        东风   1-2级  220    重度污染         5
58  2018-02-28       9      -2   多云~晴       西南风   3-4级  139    轻度污染         3

In [132]:
t[condition].head()

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel
31  2018-02-01       4      -7     多云        北风   1-2级   68       良         2
32  2018-02-02      -1      -9      晴        北风   3-4级   32       优         1
33  2018-02-03       0      -9     多云        北风   1-2级   24       优         1
34  2018-02-04       1      -8      晴       西南风   1-2级   36       优         1
35  2018-02-05       0     -10      晴        北风   3-4级   24       优         1

In [133]:
t["ymd"].str.replace("-","")

0      20180101
1      20180102
2      20180103
3      20180104
4      20180105
         ...   
360    20181227
361    20181228
362    20181229
363    20181230
364    20181231
Name: ymd, Length: 365, dtype: object

In [134]:
t

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel
0    2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良         2
1    2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优         1
2    2018-01-03       2      -5     多云        北风   1-2级   28       优         1
3    2018-01-04       0      -8      阴       东北风   1-2级   28       优         1
4    2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优         1
..          ...     ...     ...    ...       ...    ...  ...     ...       ...
360  2018-12-27      -5     -12   多云~晴       西北风     3级   48       优         1
361  2018-12-28      -3     -11      晴       西北风     3级   40       优         1
362  2018-12-29      -3     -12      晴       西北风     2级   29       优         1
363  2018-12-30      -2     -11   晴~多云       东北风     1级   31       优         1
364  2018-12-31      -2     -10     多云       东北风     1级   56       良         2

[365 rows x 9 columns]

In [135]:
m=t["ymd"].str.replace("-","")
type(m)

pandas.core.series.Series

In [136]:
m[0:6]

0    20180101
1    20180102
2    20180103
3    20180104
4    20180105
5    20180106
Name: ymd, dtype: object

In [137]:
t["ymd"].str.replace("-","").str.slice(0,6)
#只要字符串前六位

0      201801
1      201801
2      201801
3      201801
4      201801
        ...  
360    201812
361    201812
362    201812
363    201812
364    201812
Name: ymd, Length: 365, dtype: object

In [138]:
t["ymd"].str.replace("-","")[0:6]

0    20180101
1    20180102
2    20180103
3    20180104
4    20180105
5    20180106
Name: ymd, dtype: object

In [139]:
t["ymd"].str.replace("-","").str[0:6]

0      201801
1      201801
2      201801
3      201801
4      201801
        ...  
360    201812
361    201812
362    201812
363    201812
364    201812
Name: ymd, Length: 365, dtype: object

# 使用正则表达式的处理

In [140]:
#通过函数添加新列
def get_nianyueri(x):
    year,month,day=x["ymd"].split("-")
    return f"{year}年{month}月{day}日"

In [141]:
t["中文日期"]=t.apply(get_nianyueri,axis=1)
t

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  \
0    2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良   
1    2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优   
2    2018-01-03       2      -5     多云        北风   1-2级   28       优   
3    2018-01-04       0      -8      阴       东北风   1-2级   28       优   
4    2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优   
..          ...     ...     ...    ...       ...    ...  ...     ...   
360  2018-12-27      -5     -12   多云~晴       西北风     3级   48       优   
361  2018-12-28      -3     -11      晴       西北风     3级   40       优   
362  2018-12-29      -3     -12      晴       西北风     2级   29       优   
363  2018-12-30      -2     -11   晴~多云       东北风     1级   31       优   
364  2018-12-31      -2     -10     多云       东北风     1级   56       良   

     aqiLevel         中文日期  
0           2  2018年01月01日  
1           1  2018年01月02日  
2           1  2018年01月03日  
3           1  2018年01月04日  
4           1  2018年01月05日  
..        ...          ...  
360         1  2018年12月27日  
361         1  2018年12月28日  
362         1  2018年12月29日  
363         1  2018年12月30日  
364         2  2018年12月31日  

[365 rows x 10 columns]

### 如何让替换年月日

In [142]:
#链式replace
t["中文日期"].str.replace("年","").str.replace("月","").str.replace("日","")

0      20180101
1      20180102
2      20180103
3      20180104
4      20180105
         ...   
360    20181227
361    20181228
362    20181229
363    20181230
364    20181231
Name: 中文日期, Length: 365, dtype: object

In [143]:
t

ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  \
0    2018-01-01       3      -6   晴~多云       东北风   1-2级   59       良   
1    2018-01-02       2      -5   阴~多云       东北风   1-2级   49       优   
2    2018-01-03       2      -5     多云        北风   1-2级   28       优   
3    2018-01-04       0      -8      阴       东北风   1-2级   28       优   
4    2018-01-05       3      -6   多云~晴       西北风   1-2级   50       优   
..          ...     ...     ...    ...       ...    ...  ...     ...   
360  2018-12-27      -5     -12   多云~晴       西北风     3级   48       优   
361  2018-12-28      -3     -11      晴       西北风     3级   40       优   
362  2018-12-29      -3     -12      晴       西北风     2级   29       优   
363  2018-12-30      -2     -11   晴~多云       东北风     1级   31       优   
364  2018-12-31      -2     -10     多云       东北风     1级   56       良   

     aqiLevel         中文日期  
0           2  2018年01月01日  
1           1  2018年01月02日  
2           1  2018年01月03日  
3           1  2018年01月04日  
4           1  2018年01月05日  
..        ...          ...  
360         1  2018年12月27日  
361         1  2018年12月28日  
362         1  2018年12月29日  
363         1  2018年12月30日  
364         2  2018年12月31日  

[365 rows x 10 columns]

In [144]:
#正则表达式替换
t["中文日期"].str.replace("[年月日]","")
#这个警告信息 "FutureWarning: The default value of regex will change from True to False in a future version." 意味着在未来的版本中，Pandas 库中的默认正则表达式标志将从 True 改为 False。这个警告是在提醒你在未来的版本中使用 Pandas 库时要注意这个变化。

C:\Users\A\AppData\Local\Temp/ipykernel_19140/3707090684.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  t["中文日期"].str.replace("[年月日]","")


0      20180101
1      20180102
2      20180103
3      20180104
4      20180105
         ...   
360    20181227
361    20181228
362    20181229
363    20181230
364    20181231
Name: 中文日期, Length: 365, dtype: object

## pandas的axis参数

axis是0或者index
若为单行操作，指的某一行
若为聚合操作，指的是跨行cross rows
axis为1或者columns
若为单列操作，指的某一列
若为聚合操作，指的是cross columns
axis是啥就按照某个方向就行扫描，其他的不变

In [145]:
import pandas as pd
import numpy as np

In [146]:
q=pd.DataFrame(np.arange(12).reshape(3,4),columns=['A','B','C','D'])
q

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [147]:
q.drop("A",axis='columns')
#删除某一列

B   C   D
0  1   2   3
1  5   6   7
2  9  10  11

In [148]:
q

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [149]:
q.drop(1,axis=0)
#删除某一行

A  B   C   D
0  0  1   2   3
2  8  9  10  11

### 按照axis=0/index执行mean聚合操作

In [150]:
q

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [151]:
q.mean(axis=0)
#axis=0,实际就是聚合每一行（列索引相同的求平均数，类似于遍历

A    4.0
B    5.0
C    6.0
D    7.0
dtype: float64

### 按照axis=1/columns执行聚合操作

In [152]:
q

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [153]:
q.mean(axis=1)
#同理axis=0

0    1.5
1    5.5
2    9.5
dtype: float64

In [154]:
def get_sum_value(x):
    return x["A"]+x["B"]+x["C"]+x["D"]
q["sum_value"]=q.apply(get_sum_value,axis=1)

In [155]:
q

A  B   C   D  sum_value
0  0  1   2   3          6
1  4  5   6   7         22
2  8  9  10  11         38

### pandas中merge的使用

merge是用来拼接表格的，拼接时需要将用户信息一一对应，所以拼接的时候两张表格需要共同的识别用户的键值key，merge就是将信息一一对应匹配的过程，merge共有四种类型，inner，left，right，outer

#### inner

inner属于内连接，在拼接的过程中会取两张表的键key的交集进行拼接

In [156]:
#读取member表
import pandas as pd
b_1=pd.read_excel("./data/member.xlsx")
b_1

userid  age
0      a   23
1      b   46
2      c   32
3      d   19

In [157]:
#读取sale表
b_2=pd.read_excel("./data/sale.xlsx")
b_2

userid  payment
0      a     2000
1      c     3500

In [158]:
b_1.merge(b_2,how='inner',on='userid')

userid  age  payment
0      a   23     2000
1      c   32     3500

In [159]:
#一个用户对应多条消费记录
b_1

userid  age
0      a   23
1      b   46
2      c   32
3      d   19

In [160]:
b_3=pd.read_excel("./data/sale2.xlsx")
b_3

userid  payment
0      a     2000
1      c     3500
2      a      500
3      b     1000

In [161]:
b_1.merge(b_3,how='inner',on='userid')
#一对多时会拓展复制相应条数进行拼接

userid  age  payment
0      a   23     2000
1      a   23      500
2      b   46     1000
3      c   32     3500

#### right和left

这两种在merge中是相似的，称为左连接和右连接，且可以相互转化
1.left是指以左边表格的键为基准进行配对，若左边表格的键在右边不存在，用缺失值NaN填充
2.相反的，right是以右边表格的键为基准进行配对，如果右边表格的键在左边不存在，用缺失值NaN填充

In [162]:
b_1

userid  age
0      a   23
1      b   46
2      c   32
3      d   19

In [163]:
b_4=pd.read_excel("./data/sale3.xlsx")
b_4

userid  payment
0      a     2000
1      c     3500
2      e      600

In [164]:
b_1.merge(b_4,how='left',on='userid')

userid  age  payment
0      a   23   2000.0
1      b   46      NaN
2      c   32   3500.0
3      d   19      NaN

In [165]:
b_1.merge(b_4,how='right',on='userid')

userid   age  payment
0      a  23.0     2000
1      c  32.0     3500
2      e   NaN      600

In [166]:
b_4.merge(b_1,how='right',on='userid')

userid  payment  age
0      a   2000.0   23
1      b      NaN   46
2      c   3500.0   32
3      d      NaN   19

#### outer

outer是外连接，拼接的过程会取两张表键key的并集进行拼接

In [167]:
b_1

userid  age
0      a   23
1      b   46
2      c   32
3      d   19

In [168]:
b_4

userid  payment
0      a     2000
1      c     3500
2      e      600

In [169]:
b_1.merge(b_4,how='outer',on='userid')

userid   age  payment
0      a  23.0   2000.0
1      b  46.0      NaN
2      c  32.0   3500.0
3      d  19.0      NaN
4      e   NaN    600.0

万能公式
以key1,key2进行合并，默认inner合并，只保留两个DataFrame都有的数据
on 表示根据什么进行合并
how = {'left', 'right', 'outer', 'inner'} 可以取4个值
how='inner' 表示返回两个DataFrame都有的keys合并的结果
how='outer' 表示两个DataFrame中没有数据的地方会补充NaN
how='left' 表示给予left位置的DataFrame进行合并填充（就相当于把left的key进行合并，没有数
据的位置填充NaN）
how='right' 表示给予right位置的DataFrame进行合并填充
例如：
pd.merge(left,right,on=['key1','key2'],how='inner')

In [170]:
pd.merge(b_1,b_4,on=['userid'],how='outer')

userid   age  payment
0      a  23.0   2000.0
1      b  46.0      NaN
2      c  32.0   3500.0
3      d  19.0      NaN
4      e   NaN    600.0

#### pandas中concat函数基本介绍

pd.concat(objs,axis=0,join='outer',join_axes=None,ignore_index=False,keys=None,levels=None,names=None,verify_integrity=False)
其中：
objs：待合并的所有数据集，一般为list，list中的元素为series或者dataframe
axis：合并时参考的轴，0为基于行合并，1为基于列合并，默认为0
join：连接方式为内连接inner或者外连接outer
gnore_index：是否忽略原始索引，取值为 True 或 False，默认为 False。
其他参数暂不说明

In [171]:
import pandas as pd
import numpy as np
m=pd.DataFrame(np.arange(1,17).reshape(4,4),columns=list('ABCD'))
n=pd.DataFrame(np.arange(17,33).reshape(4,4),columns=list('ABCD'))

In [172]:
m

A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [173]:
n

A   B   C   D
0  17  18  19  20
1  21  22  23  24
2  25  26  27  28
3  29  30  31  32

In [174]:
#基于行合并
data=pd.concat([m,n])
data

A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
0  17  18  19  20
1  21  22  23  24
2  25  26  27  28
3  29  30  31  32

In [175]:
#基于列合并
data_1=pd.concat([m,n],axis=1)
data_1

A   B   C   D   A   B   C   D
0   1   2   3   4  17  18  19  20
1   5   6   7   8  21  22  23  24
2   9  10  11  12  25  26  27  28
3  13  14  15  16  29  30  31  32

In [176]:
#内连接inner取交集
#我们先重新定义m的索引
m.rename(index={0:1,1:2,2:3,3:4},inplace=True)
m

A   B   C   D
1   1   2   3   4
2   5   6   7   8
3   9  10  11  12
4  13  14  15  16

In [177]:
n

A   B   C   D
0  17  18  19  20
1  21  22  23  24
2  25  26  27  28
3  29  30  31  32

In [178]:
data_2=pd.concat([m,n],axis=1,join='inner')
data_2

A   B   C   D   A   B   C   D
1  1   2   3   4  21  22  23  24
2  5   6   7   8  25  26  27  28
3  9  10  11  12  29  30  31  32

In [179]:
#外连接outer取并集，无数据用NaN填充
data_3=pd.concat([m,n],axis=1,join='outer')
data_3

A     B     C     D     A     B     C     D
0   NaN   NaN   NaN   NaN  17.0  18.0  19.0  20.0
1   1.0   2.0   3.0   4.0  21.0  22.0  23.0  24.0
2   5.0   6.0   7.0   8.0  25.0  26.0  27.0  28.0
3   9.0  10.0  11.0  12.0  29.0  30.0  31.0  32.0
4  13.0  14.0  15.0  16.0   NaN   NaN   NaN   NaN

In [180]:
#指定根据哪个轴来对齐数据
#引入join_sxes参数，join_axes=[m,index]为保留m的轴，n将根据m的index进行合并
data_4=pd.concat([m,n],axis=1).reindex(m.index)
data_4

A     B     C     D     A     B     C     D
1   1.0   2.0   3.0   4.0  21.0  22.0  23.0  24.0
2   5.0   6.0   7.0   8.0  25.0  26.0  27.0  28.0
3   9.0  10.0  11.0  12.0  29.0  30.0  31.0  32.0
4  13.0  14.0  15.0  16.0   NaN   NaN   NaN   NaN

在数据处理和分析中，merge和concat都是将不同的数据合并在一起的方法，但它们的实现方式和效果略有不同。

merge是将两个或多个数据集按照一定的条件进行连接，通常需要指定连接的键（key）或索引（index），它可以实现多种不同类型的连接，包括内连接、左连接、右连接和外连接等。merge通常用于将不同数据集中的信息按照某种关系进行关联，类似于SQL语句中的JOIN操作。

而concat则是将两个或多个数据集沿着某个轴（通常是行轴或列轴）进行简单的堆叠，它不需要指定连接的键或索引，只需确保合并的数据集具有相同的轴标签即可。concat通常用于将多个数据集拼接在一起，形成一个更大的数据集，类似于SQL语句中的UNION操作。

因此，merge和concat的主要区别在于它们的连接方式和合并方式不同。在具体应用中，需要根据数据集的特点和需求选择合适的方法来进行数据合并。

#### groupby用法

In [182]:
data_5=pd.read_excel("./data/group.xlsx")
data_5

company  salary  age
0       C      43   35
1       C      17   25
2       C       8   30
3       A      20   22
4       B      10   17
5       B      21   40
6       A      23   33
7       C      49   19
8       B       8   30

In [183]:
group=data_5.groupby("company")

In [186]:
type(group)

pandas.core.groupby.generic.DataFrameGroupBy

In [185]:
list(group)

[('A',
    company  salary  age
  3       A      20   22
  6       A      23   33),
 ('B',
    company  salary  age
  4       B      10   17
  5       B      21   40
  8       B       8   30),
 ('C',
    company  salary  age
  0       C      43   35
  1       C      17   25
  2       C       8   30
  7       C      49   19)]

In [187]:
data_5.groupby("company").agg('mean')

salary    age
company               
A         21.50  27.50
B         13.00  29.00
C         29.25  27.25

In [188]:
data_5.groupby('company').agg({'salary':'median','age':'mean'})

salary    age
company               
A          21.5  27.50
B          10.0  29.00
C          30.0  27.25

### 去重处理

In [189]:
import pandas as pd
import numpy as np

In [190]:
y=pd.DataFrame({'A':[1,1,1,2,2,3,1],'B':list("aabbbca")})
y

A  B
0  1  a
1  1  a
2  1  b
3  2  b
4  2  b
5  3  c
6  1  a

In [191]:
#判断每一行是否重复，结果为True和false
y.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [192]:
#判断重复的行数
y.duplicated().sum()

3

In [193]:
#去除全部的重复行
y.drop_duplicates()

A  B
0  1  a
2  1  b
3  2  b
5  3  c

In [194]:
#去除指定行
y.drop_duplicates(['A'])

A  B
0  1  a
3  2  b
5  3  c

keep：有三个可选参数，分别是 first、last、False，默认为 first，表示只保留第一次出现的重复项，删除其余重复项，last 表示只保留最后一次出现的重复项，False 则表示删除所有重复项。